name: push-new-tag
on:
  push:
    branches:
      - 32bit
jobs:
  xgo:
    strategy:
      matrix:
        go_version:
          - 1.13.x
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v1
      -
        name: Build with xgo
        uses: crazy-max/ghaction-xgo@v1
        with:
          xgo_version: latest
          go_version: ${{ matrix.go_version }}
          dest: build
          prefix: decrypo
          targets: windows/386
          v: true
          x: false
          ldflags: -s -w
      - 
        name: Upload Artifacts
        uses: actions/upload-artifact@v1
        with:
          path: build
